### ISSUE TITLE
Can't add Jakarta

### ISSUE THREAD

**Issue by frankrousseau** [pierrerousseau/owm#1]
Hi there,

When I enter Jakarta, capital of Indonesia, it doesn't work properly. Half of the information are not properly displayed. Do you have any idea of what's wrong?

By the way the new design is great!

**Comment by pierrerousseau** [comment]
OWM send sometimes weather conditions that are not described in their api, so I can't predict them and I can't show them. I will look for a default weather condition in order to make it look less disturbing.

**Comment by pierrerousseau** [comment]
I found a few mistakes, it should be corrected now and working. Feel free to open a new issue if I'm wrong.
