### ISSUE TITLE
Different (and weird) values than openweathermap.org

### ISSUE THREAD

**Issue by nicofrand** [pierrerousseau/owm#3]
OWM retrieves the values from OpenWeatherMap but the values differ (and the values in Cozy are weird).

Here, on 2016-01-05 in my cozy for "Nice,fr", I can clearly read some negative values during the night:

![owm-bug-cozy](https://cloud.githubusercontent.com/assets/3419050/12117078/828bbaba-b3be-11e5-9c02-20fac99e9b35.png)

Here, at the same moment (10 seconds later really, just the time to refresh the page) on [OpenWeatherMap](https://openweathermap.org/city/2990440), the values are all positive (and I believe, more accurate):

![owm-bug-source](https://cloud.githubusercontent.com/assets/3419050/12117113/ad66d4a4-b3be-11e5-903c-9e8576094cf5.png)

The request made by the browser to [/apps/pr-owm/cities](https://cozy.nicofrand.eu/apps/pr-owm/cities) seem to return the same values as displayed in Cozy (after translating into Celsius): 

![owm-bug2](https://cloud.githubusercontent.com/assets/3419050/12117336/76adfd6e-b3c0-11e5-8788-4e149f42e12e.png)

273.27 Kelvin = -0,15 Celsius.

**Comment by pierrerousseau** [comment]
it seems that I have "sometimes" different values for this url : 
http://api.openweathermap.org/data/2.5/forecast?units=metric&id=6454924&appid=2de143494c0b295cca9337e1e96b00e0
and this one : 
http://api.openweathermap.org/data/2.5/forecast/?units=metric&id=6454924&appid=2de143494c0b295cca9337e1e96b00e0

I use the second (except the appid), but I checked in openweathermap doc and they use the first one. So I will change it, but I do not really understand why it is so. Moreover it changes (now i can get +3° just by refreshing the url).

Before I change anything, can you tell me if you get different values from these two urls ? and if it changes ?

**Comment by nicofrand** [comment]
I can't for the moment (not easy on mobile), until Monday. But I guess you found the bug :).

Do you know if there is a way to contact them too and ask about the differences between the URLs ?

**Comment by pierrerousseau** [comment]
I pushed an update of owm, can you confirm that it solves your issue ? (remove reinstall or wait for cozy notification)

No, I have no idea if I can contact them, and not time for it to be honest ...

**Comment by nicofrand** [comment]
As far as I can tell by checking tonight's weather, everything seems OK, thanks !

**Comment by pierrerousseau** [comment]
thanks for reporting :+1:

**Comment by pierrerousseau** [comment]
@nicofrand , not long after this change, i started to have very strange values, and most of the time it's not working at all, do you still use the app and if yes, is it working for you ?

**Comment by nicofrand** [comment]
I don't really use it anymore. The values sometimes seem strange to mee though but they look weird on OWM's website too…
